services:
  app:
    container_name: app
    user: root
    build:
      context: .docker
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www
    tty: true

  database:
    image: postgres:16.3-alpine3.20
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'